### ISSUE TITLE
Got nil ViSearchResult.reqId

### ISSUE THREAD

**Issue by RR12** [visenze/visearch-sdk-ios#28]
Hi, i have a problem when i use ViSearchAPI I got nil **reqId** .

```
[ViSearchAPI setupAccessKey:kServiceAccessKey andSecretKey:kServiceSecretKey];
...
SearchParams *params = [self createSearchParamsWithProductId:productId];
[[ViSearchAPI defaultClient] searchWithImageId:params success:^(NSInteger statusCode, ViSearchResult *data, NSError *error) {
    // data.reqId is nil
} failure:^(NSInteger statusCode, ViSearchResult *data, NSError *error) {

}];
```

I want to implement User action tracking, so as I understand that I need that reqId to call the tracking method 
`[TrackParams createWithCID:client.accessKey ReqId:requestId andAction:action];`

Anyone have found this and know which part did I miss? Thanks in advance.

FYI:
`pod 'ViSearch', '~>1.0.0'`
Here is what I got from **pod install**
`Installing ViSearch (1.0.10)`

When I tried to use version 1.1.0 I got error like this

```
Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `ViSearch (~> 1.1.0)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `ViSearch (~> 1.1.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
```

**Comment by yulu** [comment]
@thehung111  could you please look at the issue

**Comment by thehung111** [comment]
Hi,

The pod version should be 1.1.0. 

```
pod 'ViSearch', '~>1.1.0'
```

Can you try pod install after that? Alternately you can just copy directly from source code.
You need to obtain a recent request id for tracking e.g. you first call search, a list of images come out, then you call tracking for clicking on the image.

Please see example for tracking here here:

https://github.com/visenze/visearch-sdk-ios/blob/a1c5996193a6c1623b7ec46bf25f00e89eeb85b5/NewExample/ViSearchExample/DemoApp/ResultViewController.m#L857

**Comment by thehung111** [comment]
Another possible reason is that there is an error in the API call. Can you check data.error e.g.

(data.error == nil ? @"An error has occured" : [NSString stringWithFormat:@"An error has occured: \n%@", data.error.message ]

**Comment by RR12** [comment]
Thanks @yulu @thehung111 for your reply.

I have tried to update the pod to version '1.1.0' but as a mention above, I got that erros (also posted in my first post.)
I have checked the data.error is nil.

**Comment by thehung111** [comment]
Can you post your pod file here? Just want to see if there is any error in your pod.
Anyway can you try `pod repo update` as recommended to see if it help ?
I just tried to pod install, it is working fine for me on a new project. You should use version 1.1.0 as there is a bug in earlier version which does not show the error messages properly.

**Comment by RR12** [comment]
Hi @thehung111 sorry for this late reply. Looks like `pod repo update` solve the updating to 1.1.0 issue. And now I can get the request Id. Thank you so much.

**Comment by thehung111** [comment]
great, I will close the issue :)

**Comment by RR12** [comment]
Sorry @thehung111 @yulu  , I still have one last question. :) 
I have implement the tracking code, but I don't know how and where to check is it work or not. 
As I refer from this page https://developers.visenze.com/guides/guide/2016/03/31/event-tracking.html it should be under **Reports** menu. But there's only 2 item in my Reports menu and there's no **Event Tracking** .
Sorry, I know this is not SDK issue.
Thanks in advance.

**Comment by thehung111** [comment]
You can verify by clicking on the Usage Statistics option by verifying the QPS, CTR (click through rate). The UI has changed and the documentation is a bit outdated. The stats will only update hourly so your action will not appear immediately on the graphs. It also count multiple clicks for the same search within the same session as only 1 click so do not be alarmed if you clicked multiple images but only see a very small number. Anyways, there will be new documentation available in the next few weeks. For now, you can safely assume that tracking work if you do not see any errors returned in the call back.

**Comment by RR12** [comment]
Oh okay, so if in this part, the success == YES, I can assume that the tracking is success, right?
```
[client track:params completion:^(BOOL success) {
    NSLog(success ? @"Tracking success" : @"Tracking failed");
}];
```

**Comment by thehung111** [comment]
yes, you can assume it is successful.

**Comment by RR12** [comment]
Ok. thank you so much @thehung111 .
