### ISSUE TITLE
Box value stripped when search by im_url

### ISSUE THREAD

**Issue by khemarin** [visenze/visearch-sdk-ios#44]
When using upload search providing `im_url` box parameters is not included in the request.

**Comment by thehung111** [comment]
hi @khemarin ,

Can you provide some sample code to demonstrate the issue?
The box parameters should be sent if you specify it in the API request.

**Comment by khemarin** [comment]
@thehung111 , 
Excuse me for not giving enough information. The issue is when only `im_url` is presented. 
I have not tested with `im_id` but it might be the same.
Please find the sample code below:
```swift
let key = ""
ViSearchAPI.setupAppKey(key)

let box = Box(x1: 20, y1: 20, x2: 40, y2: 50)
let uploadParams = UploadSearchParams()
uploadParams?.box = box
uploadParams?.imageUrl = "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/image/AppleInc/aos/published/images/i/ph/iphone/xr/iphone-xr-white-select-201809"

let client = ViSearchAPI.defaultClient()
client?.search(withImageUrl: uploadParams, success: { (_, result, _) in
   print(result)
 }, failure: { (_, _, error) in
    print(error?.localizedDescription)
})
```
Please let me know if anything I missed. 
Thanks,

**Comment by thehung111** [comment]
oh yes, it is a bug, let me fix this. Meanwhile, you can also use the newer SDK in Swift or set the custom parameter: https://github.com/visenze/visearch-sdk-swift

**Comment by khemarin** [comment]
Thank you for your suggestions. I am currently using custom parameter as a workaround. I will try to use swift version of the SDK in the future 👍.

**Comment by thehung111** [comment]
hi @khemarin ,

Can you update the version to 1.4.3? It should work now.

**Comment by khemarin** [comment]
Thanks for the fix @thehung111
